{{- range .Values.admissionControllers -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-{{ .name }}
  labels:
    app.kubernetes.io/name: webhook-{{ .name }}
    app.kubernetes.io/component: webhook
spec:
  replicas: {{default .replicaCount 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook-{{ .name }}
      app.kubernetes.io/component: webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webhook-{{ .name }}
        app.kubernetes.io/component: webhook
    spec:
      serviceAccountName: webhook
      containers:
        - name: webhook-{{ .name }}
          image: {{ .imageName }}
          imagePullPolicy: Always
          args: ["-tls_crt","/etc/certs/tls.crt","-tls_priv_key","/etc/certs/tls.key"]
          ports:
            - name: https
              # see https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters
              # By default, firewall rules restrict your cluster control plane to only initiate TCP connections to your nodes and Pods on ports 443 (HTTPS) and 10250 (kubelet).
              containerPort: {{ default .port 10250 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: webhook-cert
              mountPath: /etc/certs
              readOnly: true
      volumes:
        - name: webhook-cert
          secret:
            secretName: webhook-cert-{{ .name }}
---
{{- end }}
