{{- range .Values.admissionControllers -}}
apiVersion: v1
kind: Service
metadata:
  name: webhook-{{ .name }}
  labels:
    app.kubernetes.io/name: webhook-{{ .name }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: webhook-{{ .name }}
    app.kubernetes.io/component: webhook
{{- end }}
